# Generated by Django 5.0.3 on 2024-11-11 03:50

import ckeditor.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='article_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('category_status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'article_categories',
                'ordering': ['published_date'],
            },
        ),
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('body', ckeditor.fields.RichTextField()),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('article_published_status', models.CharField(choices=[('Published', 'PUBLISHED'), ('Unpublished', 'UNPUBLISHED')], default='Unpublished', max_length=20)),
                ('article_thumbnail_image', models.ImageField(blank=True, null=True, upload_to='core/article', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'JPEG', 'svg'])])),
                ('article_document_file', models.FileField(blank=True, null=True, upload_to='core/article', validators=[django.core.validators.FileExtensionValidator(['pdf', 'zip', 'csv', 'xls', 'ppt', 'html'])])),
                ('article_category_belongs_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.article_category')),
            ],
            options={
                'verbose_name_plural': 'articles',
                'ordering': ['published_date'],
            },
        ),
    ]
